### ISSUE TITLE
python setup.py install ERROR Windows

### ISSUE THREAD

**Issue by jacobpodhraski** [andrewssobral/bgslibrary#142]
running install
running bdist_egg
running egg_info
writing bgs.egg-info\PKG-INFO
writing dependency_links to bgs.egg-info\dependency_links.txt
writing top-level names to bgs.egg-info\top_level.txt
reading manifest file 'bgs.egg-info\SOURCES.txt'
writing manifest file 'bgs.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
CMake Error at CMakeLists.txt:3 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Python/bgslibrary-master/bgslibrary-master/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    keywords=['BGSLibrary', 'Background Subtraction', 'Computer Vision', 'Machine Learning'],
  File "C:\Conda\Packages\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Conda\Packages\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Conda\Packages\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Conda\Packages\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Conda\Packages\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Conda\Packages\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Conda\Packages\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Conda\Packages\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Conda\Packages\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Conda\Packages\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Conda\Packages\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Conda\Packages\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Conda\Packages\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Conda\Packages\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Conda\Packages\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Conda\Packages\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 45, in run
    self.build_extension(ext)
  File "setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\Conda\Packages\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Python\\bgslibrary-master\\bgslibrary-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Python\\bgslibrary-master\\bgslibrary-master\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=C:\\Conda\\Packages\\python.exe', '-DBGS_PYTHON_SUPPORT=ON', '-DBGS_PYTHON_VERSION=3.6', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Python\\bgslibrary-master\\bgslibrary-master\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.

**Comment by andrewssobral** [comment]
Hi @jacobpodhraski ,

Unfortunately, setup.py does not support windows yet. If you want to build bgslibrary (with python support) on windows, I suggest you to follow the instructions below:

https://github.com/andrewssobral/bgslibrary/wiki/Installation-instructions---Windows
and
https://github.com/andrewssobral/bgslibrary/wiki/Wrapper:-Python

There is also a video tutorial:

Compiling BGSLibrary with Python support on Windows 10 and MSVS 2017
https://www.youtube.com/watch?v=896Sg-4EiZE

**Comment by jacobpodhraski** [comment]
Okay thanks, I am walking through your video but I cannot seem to make out your installation lines. Do I have this correct? I see a -D in there but its throwing me an error. 

-- Configuring incomplete, errors occurred!
See also "C:/Python/bgslibrary-master/bgslibrary-master/build_win64/CMakeFiles/CMakeOutput.log".

(base) C:\Python\bgslibrary-master\bgslibrary-master\build_win64>cmake -D BGS_PYTHON_SUPPORT-ON .. -G "Visual Studio 15 2017 Win64"
Parse error in command line argument: -D
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.

**Comment by andrewssobral** [comment]
The problem is in the following line:
```cmake -D BGS_PYTHON_SUPPORT-ON .. -G "Visual Studio 15 2017 Win64"```
the correct is:
```cmake -D BGS_PYTHON_SUPPORT=ON .. -G "Visual Studio 15 2017 Win64"```

**Comment by jacobpodhraski** [comment]
Which directory should I have opencv folder in?
(base) C:\Python\bgslibrary-master\bgslibrary-master\build_win64>cmake -D BGS_PYTHON_SUPPORT=ON .. -G "Visual Studio 15 2017 Win64"
--
-- BGSLIBRARY WITH PYTHON SUPPORT: ON
-- PYTHON VERSION: 3
CMake Error at CMakeLists.txt:77 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "C:/Python/bgslibrary-master/bgslibrary-master/build_win64/CMakeFiles/CMakeOutput.log".

**Comment by andrewssobral** [comment]
You need to specify it before running cmake:

```
set OpenCV_DIR=C:\OpenCV3.2.0\build           (if you have OpenCV 3.2.0 in C:\)
set PATH=%PATH%;%OpenCV_DIR%\x64\vc15\bin     (if you are using Visual Studio 2017 x64)
```
Next:
```
cmake -DOpenCV_DIR=%OpenCV_DIR% -DBGS_PYTHON_SUPPORT=ON -G "Visual Studio 15 2017 Win64" ..
```

If you don't want the python wrapper, you can ignore the following parameter `-DBGS_PYTHON_SUPPORT=ON`. Note that the your python must be located in your system path, and you need to have the opencv lib previously installed in your python package to be able to run the python demos.

Note:

Don't forget to clone the bgslibrary repository with the `--recursive` parameter, like this:
```
git clone --recursive https://github.com/andrewssobral/bgslibrary.git
```

**Comment by jacobpodhraski** [comment]
Trying to make sense of this error now. I am not getting all of the files requried to proceed. Where should I set numpy in the path:

-- BGSLIBRARY WITH PYTHON SUPPORT: ON
-- PYTHON VERSION: 3
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 3.4.2 in C:/opencv/build/x64/vc15/lib
-- You might need to add C:\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
--
-- OpenCV library status:
--     version: 3.4.2
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_world
--     include path: C:/opencv/build/include;C:/opencv/build/include/opencv

CMake Error at CMakeLists.txt:120 (add_subdirectory):
  The source directory

    C:/Python/bgslibrary-master/bgslibrary-master/pybind11

  does not contain a CMakeLists.txt file.


--
-- Python library status:
--     executable:
--     library:
--     include path:
-- NUMPY_INCLUDE_DIR: Process failed because: The parameter is incorrect

for command:  -c "import numpy; print(numpy.get_include())"

CMake Error at CMakeLists.txt:189 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "C:/Python/bgslibrary-master/bgslibrary-master/build_win64/CMakeFiles/CMakeOutput.log".
See also "C:/Python/bgslibrary-master/bgslibrary-master/build_win64/CMakeFiles/CMakeError.log".

**Comment by andrewssobral** [comment]
This error occurs when your local python was not found by CMake, as can be seen here:
```
-- Python library status: <EMPTY>
-- executable: <EMPTY>
-- library: <EMPTY>
-- include path: <EMPTY>
...
```
As you can see, everything is empty.

You can try the following solution by adding `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` as a CMake parameter:
```
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
```
Fore more info: https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries
